title: Yuxiang (Isaac) Wu # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  Not everything that can be counted counts, and not everything that counts can be counted. - Albert Einstein
  <br><br>
  <a href="https://www.linkedin.com/in/yuxiangisaacwu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-172477568-1 # your Google Analytics tracking ID here
