title: Yuxiang (Isaac) Wu # your name (or website title) here
logo: "/images/round profile picture2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  I am a recent engineering graduate of the University of Alberta. 
  My study and work have involved a substantial amount of data collected from experiments, operations, and simulations, and I enjoy taking logical approaches to analyze, model, and visualize data, as well as communicating the results with stakeholders. 
  Before pursuing my bachelor’s degree in engineering, I have earned a business diploma in accounting. 
  The financial concepts and accounting knowledge I learned have helped me to better understand and analyze problems from a business perspective. 
  People who have worked with me would describe me as an analytical, reliable individual who maintains a positive, proactive attitude when faced with adversity. 
  Currently, I am looking for opportunities that can make positive impacts on organizations with my skills and abilities. 
  <br><br>
  <a href="https://www.linkedin.com/in/yuxiangisaacwu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-172477568-1 # your Google Analytics tracking ID here
