title: Yuxiang (Isaac) Wu # your name (or website title) here
logo: "/images/round profile picture2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  I enjoy working with data! 
  <br><br>
  <a href="https://www.linkedin.com/in/yuxiangisaacwu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-172477568-1 # your Google Analytics tracking ID here
